id: P006828
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 12:25:17.300302
source_metadata:
  id: bdr:W3CN6840
  title: བྱ་ཐ་རྐང་དང་ཕོ་རོག་གི་སྒྲུང་།
  author: ''
  volumes:
    b6e1d3b5b9cf49bea54d9cb0d546732e:
      image_group_id: I3CN6842
      title: ''
      volume_number: 1
      total_pages: 66
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessRestrictedTemporarily
  restrictedInChina: false
