id: P006828
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN6840
  title: བྱ་ཐ་རྐང་དང་ཕོ་རོག་གི་སྒྲུང་།
  author: ''
  volumes:
    b6e1d3b5b9cf49bea54d9cb0d546732e:
      image_group_id: I3CN6842
      title: ''
      volume_number: 1
      total_pages: 66
